#!/bin/bash
# Script for generating a mooc-strapi project
echo "What is your project name?"
read project_name
bucket_name="${project_name}-mooc"
echo "creating aws bucket ${bucket_name}"
bucket_result=`aws s3api create-bucket --bucket $bucket_name --acl public-read --region ca-central-1 --create-bucket-configuration LocationConstraint=ca-central-1`
echo $bucket_result
if [ -z `echo $bucket_result | jq -r '.Location'` ]
then
exit 1
fi
policy_template=`cat mooc-strapi-resources/policy.json`
policy=${policy_template//bucket-name/$bucket_name}
echo $policy > policy_temp
policy_result=`aws iam create-policy --policy-name $project_name --policy-document file://policy_temp`
rm policy_temp
echo $policy_result
policy_arn=`echo $policy_result | jq -r '.Policy.Arn'`
if [ -z policy_arn ]
then
exit 1
fi
aws iam create-user --user-name $project_name
aws iam attach-user-policy --user-name $project_name --policy-arn $policy_arn
access_key_result=`aws iam create-access-key --user-name $project_name`
echo $access_key_result
AWS_ACCESS_KEY_ID=`echo $access_key_result | jq -r '.AccessKey.AccessKeyId'`
AWS_ACCESS_SECRET=`echo $access_key_result | jq -r '.AccessKey.SecretAccessKey'`
if [ -z AWS_ACCESS_KEY_ID ]
then
exit 1
fi
npx create-strapi-app@4.9.0 $project_name --quickstart --no-run
# npx create-strapi-app@latest $project_name --template https://github.com/sunsq1991/strapi-template-mooc --quickstart --no-run
cd $project_name
echo "AWS_BUCKET=${bucket_name}" >> .env
echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
echo "AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}" >> .env
npm install @strapi/provider-email-sendgrid@4.9.0 --save
npm install @strapi/provider-upload-aws-s3@4.9.0 --save
npm install pg --save
npm install pg-connection-string --save
# add dependencies for fixing runtime error
npm install --save @babel/polyfill
npm install --save @babel/runtime
# add ckeditor5 as default richtext editor
npm install @_sh/strapi-plugin-ckeditor
# uninstall sqlite3
npm uninstall better-sqlite3
# 自定义admin登录界面
cp ../mooc-strapi-resources/src/admin/app.js ./src/admin/app.js
# 自定义Logo
cp ../mooc-strapi-resources/public/logo.svg ./public/logo.svg

cp -R ../mooc-strapi-resources/config/env ./config
cp -R ../mooc-strapi-resources/config/database.js ./config/database.js

cp ../mooc-strapi-resources/config/plugins.js ./config/plugins.js
cp ../mooc-strapi-resources/config/server.js ./config/server.js
cp ../mooc-strapi-resources/config/middlewares.js ./config/middlewares.js

cp ../mooc-strapi-resources/publish-heroku ./publish-heroku
echo 'package-lock.json' >> .gitignore
echo 'yarn.lock' >> .gitignore
echo "building the project"
npm run build
echo "Project created successfully!"
echo "Now you can run 'cd $project_name' and 'npm run develop'"
# npm run develop
