#!/bin/bash
# Script for pushing a mooc-strapi project to heroku

echo "What is your heroku project name?"
read project_name
app_result=`heroku create $project_name`
echo $app_result
app_name="$(echo $app_result | grep 'https://' | cut -d / -f2- | cut -d '/' -f 2 | cut -d '.' -f 1)"
echo $app_name
if [ -z "$app_name" ]
then
exit 1
fi

git init
git add .
git commit -m "Initial Commit"
heroku addons:create jawsdb -a $app_name

env=`cat .env`
echo "$env"
heroku config:set $env -a $app_name

heroku git:remote -a $app_name
git push heroku master
heroku open -a $app_name